### ISSUE TITLE
bug: error on new server link

### ISSUE THREAD

**Issue by Eywek** [MineWeb/Plugin-Status#5]
this column https://github.com/MineWeb/Plugin-Status/blob/master/SQL/schema.php#L19 need a default value or null authorized

**Comment by NorthenFlo** [comment]
Le fichier a était édité

**Comment by Eywek** [comment]
Ça serait bien de tester quand même avant. Il faut lui permettre d'être null et non pas lui mettre une valeur par défaut. 
```Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'status-motd' can't have a default value```

**Comment by Eywek** [comment]
J'ai fix vu que tu m'as pas l'air très actif.
